# Copyright (c) 2022, Linaro Limited.
#
# SPDX-License-Identifier: MIT

header:
  version: 10

repos:
  meta-ledge-secure:
    url: https://github.com/petegriffin/meta-ledge-secure.git
    refspec: kirkstone
    path: layers/meta-ledge-secure
    layers:
     meta-ledge-secure:

  meta-secure-core:
    url: https://github.com/jiazhang0/meta-secure-core
    refspec: d0a02859719f1a2c6b98d9d9afe785ec8535ec32
    path: layers/meta-secure-core
    layers:
      meta:
      meta-tpm2:
      meta-encrypted-storage:
      meta-efi-secure-boot:
      meta-signing-key:

  meta-selinux:
    path: layers/meta-selinux
    url: http://git.yoctoproject.org/git/meta-selinux
    refspec: kirkstone

local_conf_header:
  base: |
    WKS_FILE="ledge-secure.wks.in"
